#!/bin/bash
#
# Author : Amit Mitkar
#
# Get the latest version of this script @ 
#
#         https://github.com/amitmitkar/ScriptsAndSuch/blob/master/Add%20Black%20Border
#
# This is a simple script which can be trigerred from Nautilus ( Gnome's File Browser )
# as a right click menu option.
#
# When run on image files, it will add a black border to all selected image files.
#
# It needs the ImageMagick suite of tools & zenity ( should come with Gnome) to function.
# 
# To Install, simply copy it into your ~/.gnome2/nautilus-scripts/ directory as follows:
# $> mkdir ~/.gnome2/nautilus-scripts/ImageScripts/
# $> cp 'Add Black Border' ~/.gnome2/nautilus-scripts/ImageScripts
# $> cd ~/.gnome2/nautilus-scripts/ImageScripts
# $> chmod +x 'Add Black Border'
#
# Thats it. Restart nautilus and right click on any file. You should see 
# "Scripts -> ImageScripts -> Add Black Border"
#
# This script can run on multiple files and you can invoke it from the command line too.
# It provides a progress bar that indicates the progress.
# If there are failures it will provide a list of errors once its done with all the files.
#
# To install ImageMagick & Zenity use your distro specific package manager.
# E.g. on Fedora the following probably would work.
#
# $> sudo yum install ImageMagick
# $> sudo yum install zenity


errors=0
total=$#
pid=$$


exit_func()
{
	rm /tmp/bordererrs.$pid
	rm /tmp/mogrifye$pid
	rm $fil.$pid
	exit 255
}

trap "exit_func" HUP 

while [ $# -gt 0 ]
do
	fil=$1
	convert -bordercolor \#000000 -border 3% "$fil" ${fil}.${pid} 1>&2 2> /tmp/mogrifye$pid
	if [ $? -ne 0 ]
	then
		echo "Failed file \"$fil\":" 1>>  /tmp/bordererrs.$pid
		echo "Error : "  1>>  /tmp/bordererrs.$pid
		cat /tmp/mogrifye$$  1>>  /tmp/bordererrs.$pid
		echo "--------------------------------"  1>> /tmp/bordererrs.$pid
	else
		cp ${fil}.${pid} $fil
	fi
	rm -f ${fil}.${pid}
	shift 1
	echo $((100-100*$#/$total))
done |  zenity --progress --title "Adding borders" --auto-kill --auto-close

if [ -f /tmp/bordererrs.$pid ]
then
	zenity --text-info --title 'Failed on some files' --filename /tmp/bordererrs.$pid
fi

rm -f /tmp/mogrifye$pid /tmp/bordererrs.$pid
